var tea = "Milk Tea";
console.log("Is tea == 'Milk Tea'? I predict True");
console.log(tea == "Milk Tea");
var pouch = "Brushes";
console.log("Is pouch == 'Brushes'? I say yes");
console.log(pouch == "Brushes");
var classRoom = "Students";
console.log("Is classRoom == 'Students'? I predict True");
console.log(classRoom == "Students");
var regulator = "Fast";
console.log("Is regulator == 'Fast'? I predict True");
console.log(regulator == "Fast");
var room = "Empty";
console.log("Is room == 'Empty'? I say True");
console.log(room == "Empty");
var secondRoom = "Empty";
console.log("Is secondRoom == 'Not Empty'? I say False");
console.log(secondRoom == "Not Empty");
var karachi = "Big City";
console.log("Is karachi == 'small city'? I predict False");
console.log(karachi == "small city");
var internet = "expensive";
console.log("Is internet == 'cheap'? I say false");
console.log(internet == "cheap");
var weather = "Cold";
console.log("Is weather == 'Hot'? I predict false");
console.log(weather == "Hot");
var drawer = "open";
console.log("Is drawer == 'close'? I predict false");
console.log(drawer == "close");
